import os

ANUBIS_PUBLIC_KEY = os.getenv("ANUBIS_PUBLIC_KEY")
ANUBIS_PRIVATE_KEY = os.getenv("ANUBIS_PRIVATE_KEY")

FIXED_FEE = 2.50
PERCENTAGE_COMMISSION = 0.15
MINIMUM_VALUE = 20.00

ANUBIS_API_URL = "https://api.anubispay.com.br/v1"
